lita:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  #Joint controllers' definition
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_shoulder_roll
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
  # joint2_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: l_shoulder_pitch
  #   pid: {p: 100.0, i: 0.01, d: 10.0}

  # joint3_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: l_shoulder_yaw
  #   pid: {p: 100.0, i: 0.01, d: 10.0}

  # joint4_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: l_elbow
  #   pid: {p: 100.0, i: 0.01, d: 10.0}

  # joint5_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: l_wrist_roll
  #   pid: {p: 100.0, i: 0.01, d: 10.0}

  # joint6_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: l_wrist_pitch
  #   pid: {p: 100.0, i: 0.01, d: 10.0}

  # joint7_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: l_wrist_yaw
  #   pid: {p: 100.0, i: 0.01, d: 10.0}

  # joint8_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: r_shoulder_roll
  #   pid: {p: 100.0, i: 0.01, d: 10.0}
  
  # joint9_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: r_shoulder_pitch
  #   pid: {p: 100.0, i: 0.01, d: 10.0}

  # joint10_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: r_shoulder_yaw
  #   pid: {p: 100.0, i: 0.01, d: 10.0}

  # joint11_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: r_elbow
  #   pid: {p: 100.0, i: 0.01, d: 10.0}

  # joint12_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: r_wrist_roll
  #   pid: {p: 100.0, i: 0.01, d: 10.0}

  # joint13_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: r_wrist_pitch
  #   pid: {p: 100.0, i: 0.01, d: 10.0}

  # joint14_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: r_wrist_yaw
  #   pid: {p: 100.0, i: 0.01, d: 10.0}
