controller_joint_names: ['l_shoulder_roll', 'l_shoulder_pitch', 'l_shoulder_yaw', 'l_elbow', 'l_wrist_roll', 'l_wrist_pitch', 'l_wrist_yaw', 'r_shoulder_roll', 'r_shoulder_pitch', 'r_shoulder_yaw', 'r_elbow', 'r_wrist_roll', 'r_wrist_pitch', 'r_wrist_yaw', ]
lita:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_shoulder_roll
    pid: {p:100.0, i: 0.01, d: 10.0}
  
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_shoulder_pitch
    pid: {p:100.0, i: 0.01, d: 10.0}